project_id = "yhqcwlvzcdeqxqvavcfl"

[functions.generate-content]
verify_jwt = false

[functions.generate-editorial-plan]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.comment-response]
verify_jwt = false

[functions.publish-blog]
verify_jwt = false

[functions.generate-strategic-ideas]
verify_jwt = false