project_id = "yhqcwlvzcdeqxqvavcfl"

[functions.generate-content]
verify_jwt = false

[functions.generate-editorial-plan]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.comment-response]
verify_jwt = false

[functions.publish-blog]
verify_jwt = false

[functions.generate-strategic-ideas]
verify_jwt = false

[functions.publish-social]
verify_jwt = false

[functions.unsubscribe-proxy]
verify_jwt = false

[functions.editorial-reminder]
verify_jwt = false

[functions.auto-publish-blog]
verify_jwt = false

[functions.publish-scheduled-blogs]
verify_jwt = false

[functions.publish-to-linkedin]
verify_jwt = false

[functions.publish-to-make]
verify_jwt = false